export const PokeIcons = {
  types: {
    bug: require('../assets/types/bug.png'),
    dark: require('../assets/types/dark.png'),
    dragon: require('../assets/types/dragon.png'),
    electric: require('../assets/types/electric.png'),
    fairy: require('../assets/types/fairy.png'),
    fighting: require('../assets/types/fighting.png'),
    fire: require('../assets/types/fire.png'),
    flying: require('../assets/types/flying.png'),
    ghost: require('../assets/types/ghost.png'),
    grass: require('../assets/types/grass.png'),
    ground: require('../assets/types/ground.png'),
    ice: require('../assets/types/ice.png'),
    normal: require('../assets/types/normal.png'),
    poison: require('../assets/types/poison.png'),
    psychic: require('../assets/types/psychic.png'),
    rock: require('../assets/types/rock.png'),
    steel: require('../assets/types/steel.png'),
    water: require('../assets/types/water.png'),
  },
};
